"""Deterministic teacher-report assembly for approved Sprint 3 artifacts."""

from __future__ import annotations

from .models import ClassAnalysis, GroupName
from .sprint3_evidence import class_evidence
from .sprint3_schemas import (
    ApprovalRecord,
    ExerciseArtifact,
    GroupProposalArtifact,
    PlanArtifact,
)


def build_sprint3_report(
    analysis: ClassAnalysis,
    groups: GroupProposalArtifact,
    plans: PlanArtifact,
    exercises: ExerciseArtifact,
    approvals: list[ApprovalRecord],
) -> str:
    evidence = class_evidence(analysis)
    lines = [
        "# GapBridge Teacher Report — Sprint 3",
        "",
        f"- Run ID: `{groups.run_id}`",
        f"- Assessment: {analysis.title}",
        f"- Learners: {len(analysis.learners)}",
        "- Data policy: synthetic learner IDs and scores only",
        "",
        "## Computed Class Evidence",
        "",
        "| Skill | Class average | Mastery threshold | Gap |",
        "|---|---:|---:|---|",
    ]
    for skill in evidence["skills"]:  # type: ignore[assignment]
        lines.append(
            f"| {skill['skill']} | {skill['class_average']:.2f}% | "
            f"{skill['mastery_threshold']:.2f}% | "
            f"{'Yes' if skill['is_class_gap'] else 'No'} |"
        )

    lines.extend(["", "## Approved Groups", ""])
    for group in GroupName:
        members = groups.effective_membership[group.value]
        lines.append(f"### {group.value} ({len(members)})")
        lines.append("")
        for learner_id in members:
            lines.append(f"- **{learner_id}** — {groups.rationales[learner_id]}")
        lines.append("")

    lines.extend(["## Approved Remediation Plans", ""])
    for plan in plans.draft.plans:
        lines.extend(
            [
                f"### {plan.group}",
                "",
                f"- Target skills: {', '.join(plan.target_skills)}",
                f"- Priority: {plan.priority}",
                f"- Sessions: {plan.session_count}",
                "- Objectives:",
                *[f"  - {item}" for item in plan.objectives],
                "- Strategies:",
                *[f"  - {item}" for item in plan.strategies],
                "- Session sketch:",
                *[f"  - {item}" for item in plan.session_sketch],
                "- Success criteria:",
                *[f"  - {item}" for item in plan.success_criteria],
                "",
            ]
        )

    lines.extend(["## Approved Exercise Appendix", ""])
    for exercise_set in exercises.draft.sets:
        lines.extend([f"### {exercise_set.title}", ""])
        for item in exercise_set.items:
            lines.extend(
                [
                    f"1. **[{item.skill} · {item.difficulty}]** {item.prompt}",
                    f"   - Expected answer: `{item.expected_answer}`",
                ]
            )
        lines.append("")

    lines.extend(["## Teacher Approval Record", ""])
    for approval in approvals:
        comment = f" — {approval.comment}" if approval.comment else ""
        lines.append(
            f"- **{approval.gate}**: {approval.decision} by {approval.actor} "
            f"for {approval.artifact_type} v{approval.artifact_version} "
            f"at {approval.timestamp}{comment}"
        )

    lines.extend(
        [
            "",
            "## Provenance",
            "",
            "### Remediation plans",
            "",
            f"- Generated by: `{plans.provenance.generated_by}`",
            f"- Provider: `{plans.provenance.provider}`",
            f"- Model: `{plans.provenance.model_id}`",
            f"- Agent: `{plans.provenance.agent_name or 'none'}`",
            f"- Strands SDK: `{plans.provenance.sdk_version or 'not used'}`",
            f"- Input hash: `{plans.provenance.input_hash}`",
            f"- Validation: `{plans.provenance.validation_status}`",
            f"- Tool calls: `{', '.join(plans.provenance.tool_calls) or 'none'}`",
            "",
            "### Exercises",
            "",
            f"- Generated by: `{exercises.provenance.generated_by}`",
            f"- Provider: `{exercises.provenance.provider}`",
            f"- Model: `{exercises.provenance.model_id}`",
            f"- Agent: `{exercises.provenance.agent_name or 'none'}`",
            f"- Strands SDK: `{exercises.provenance.sdk_version or 'not used'}`",
            f"- Input hash: `{exercises.provenance.input_hash}`",
            f"- Validation: `{exercises.provenance.validation_status}`",
            f"- Tool calls: `{', '.join(exercises.provenance.tool_calls) or 'none'}`",
            "",
            "> All generated teaching content is a teacher-approved draft. "
            "Official scores, gaps, grouping, transitions, and approvals are deterministic.",
            "",
        ]
    )
    return "\n".join(lines)
